---
name: Build PDF

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build PDF
        uses: xu-cheng/latex-action@v4
        with:
          root_file: cv-drusinsky.tex

      - name: Compress PDF
        run: >
          docker run --rm -v "$PWD:/workdir" ptspts/pdfsizeopt
          pdfsizeopt cv-drusinsky.pdf cv-drusinsky.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv-drusinsky
          path: cv-drusinsky.pdf
